version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest  # Usamos la imagen de Ollama
    ports:
      - '8080:8080'  # Mapeamos el puerto 8080
    environment:
      - OLLAMA_HOST=0.0.0.0:8080  # Configuramos Ollama para escuchar en todas las interfaces
    volumes:
      - ollama_data:/root/.ollama  # Persistencia de datos de Ollama

volumes:
  ollama_data:  # Definimos un volumen para persistencia
